### ISSUE TITLE
Code Error

### ISSUE THREAD

**Issue by Ledroid** [WekyDev/weky-npm#38]
Uh, so I think you guys forgot to erase something in the code of weky at the calculator file in src at the line where it says btn.reply.defer

that's basically not a function. When I changed it to btn.defer everything worked perfectly fine with me, so I would appreciate it if you fix that problem in the code before everyone go crazy wasting time seeing why the calculator thing doesn't work!

Thanks, Ledroid.

**Comment by Ledroid** [comment]
I have made sure I updated discord buttons, and it's still not working as I saw in the closed issue

**Comment by Ledroid** [comment]
![image](https://user-images.githubusercontent.com/87201247/128039541-92f2268a-c85a-4ce8-ae8d-c09695bd2a96.png)

**Comment by Ledroid** [comment]
![image](https://user-images.githubusercontent.com/87201247/128039975-80e72628-a017-4d48-8c9c-f4e4f5bcc726.png)

**Comment by face-hh** [comment]
Hello **Ledroid**, this doesn't mean that we forgot something or did something wrong, this error is caused by your old version of "discord-buttons", please upgrade to the latest version, if you see that your npm says that it is already up to date, just reinstall it. On this you will may see your errors reverted, btn.defer will not be a function, don't be scare, you can see the new changes by reading the documentation [here](https://discord-buttons.js.org/)!

If this fixed your error, feel free to close this issue on!

**Comment by Ledroid** [comment]
It worked after I reinstalled it, thanks!
