### ISSUE TITLE
Axios not found

### ISSUE THREAD

**Issue by devxsagnik** [WekyDev/weky-npm#52]
Hey devs, i wanna inform you that weky has a error of **Module Not Found Axios**.When i made a fork of it, saw that the both dependencies cheerio and axios are in devDependencies.So after replacing them in normal dependencies its working well.So please merge it with your current repo so that users should not have any problem later on.Thanks..

My package.json - 
`{
	"name": "weky",
	"version": "3.1.8",
	"description": "A fun npm package to play games within Discord with buttons!",
	"main": "index.js",
	"types": "typings/index.d.ts",
	"scripts": {
		"test": "nodemon test/test.js"
	},
	"keywords": [
		"weky",
		"discord-games"
	],
	"homepage": "https://github.com/WekyDev/weky-npm#readme",
	"license": "CC BY-NC-ND 4.0",
	"bugs": {
		"url": "https://github.com/WekyDev/weky-npm/issues"
	},
	"author": "Face#5454 + Sujal Goel#7602 + rayz#4986",
	"repository": {
		"type": "git",
		"url": "https://github.com/WekyDev/weky-npm.git"
	},
	"dependencies": {
		"chalk": "^4.1.1",
		"html-entities": "^2.3.2",
		"mathjs": "^9.4.3",
		"node-fetch": "^2.6.1",
		"quick.db": "^7.1.3",
		"cheerio": "^1.0.0-rc.10",
		"axios": "^0.21.1",
		"string-width": "^2.1.1"
	},
	"devDependencies": {
		"@weky/inlinereply": "^0.0.0",
		"nodemon": "^2.0.12"
	}
}`

**Comment by sujalgoel** [comment]
First of all, we have an npm package of this GitHub repository and we expect you to use that [npm package](https://www.npmjs.com/package/weky) and If you are forking it for doing changes then please join our Discord server and inform us so that we can also implement it for the benefit of other users and if you don't want to share it then you might have checked that `discord.js` module isn't used in `package.json` because we are getting that version from your package.json and giving you the functions depending upon your `discord.js` version, whether it's v12 or v13. So, the modules in `devDependencies` are the ones that we use in `v12` and most likely not in `v13`.

**Comment by sujalgoel** [comment]
if you have any other issues then mind joining our [Discord server](https://discord.gg/Gy5R5UEJmb) and contacting one of the developers.

**Comment by devxsagnik** [comment]
No sir, it's all ok.I just informed you about the ongoing error.If you fix it soon we can use it as it's a very useful package ;).Thank You

**Comment by sujalgoel** [comment]
well, it's not an error more like an exception or warning to download the module which you can install using 
```
npm i MODULE_NAME
```
